name: UZ FOOTBALL APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  android:
    name: Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Godot o‘rnatish
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0
          use-dotnet: false

      - name: Android export template o‘rnatish
        run: |
          godot --headless --editor --install-android-build-template

      - name: APK build qilish
        run: |
          mkdir -p build
          godot --headless --path . --export-release "Android" build/UZ-FOOTBALL.apk

      - name: APKni yuklash
        uses: actions/upload-artifact@v4
        with:
          name: UZ-FOOTBALL-APK
          path: build/UZ-FOOTBALL.apk
